(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b2)
		(clear b2)
		(clear b3)
		(on-table b5)
		(clear b5)
		(on-table b6)
		(clear b6)
		(on-table b7)
		(clear b7)
		(on-table b9)
		(clear b9)
		(in-tower t0)
		(on b4 t0)
		(in-tower b4)
		(on b8 b4)
		(in-tower b8)
		(on b0 b8)
		(in-tower b0)
		(on b1 b0)
		(in-tower b1)
		(on b3 b1)
		(in-tower b3)
		(green b3)
		(yellow b3)
		(blue b5)
		(blue b6)
		(red b9)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?y) (or (not (yellow ?y)) (exists (?x) (and (green ?x) (on ?x ?y))))) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (and (not (on b3 b4)) (not (on b9 b4)) (not (on b9 b8)) (not (on b2 b3)))))
)