(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b2)
		(clear b2)
		(clear b4)
		(on-table b5)
		(clear b5)
		(on-table b7)
		(clear b7)
		(in-tower t0)
		(on b0 t0)
		(in-tower b0)
		(on b1 b0)
		(in-tower b1)
		(on b3 b1)
		(in-tower b3)
		(on b8 b3)
		(in-tower b8)
		(on b6 b8)
		(in-tower b6)
		(on b9 b6)
		(in-tower b9)
		(on b4 b9)
		(in-tower b4)
		(blue b0)
		(blue b1)
		(green b2)
		(green b3)
		(yellow b3)
		(green b4)
		(yellow b4)
		(blue b6)
		(green b8)
		(red b9)
		(blue b5)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?y) (or (not (yellow ?y)) (exists (?x) (and (green ?x) (on ?x ?y))))) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (and (not (on b2 b3)) (not (on b4 b3)) (not (on b2 b4)))))
)