(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b0)
		(clear b0)
		(on-table b1)
		(clear b1)
		(on-table b2)
		(clear b2)
		(clear b5)
		(on-table b6)
		(clear b6)
		(on-table b7)
		(clear b7)
		(on-table b8)
		(clear b8)
		(on-table b9)
		(clear b9)
		(in-tower t0)
		(on b3 t0)
		(in-tower b3)
		(on b4 b3)
		(in-tower b4)
		(on b5 b4)
		(in-tower b5)
		(red b0)
		(maroon b0)
		(blue b1)
		(green b1)
		(red b2)
		(maroon b2)
		(blue b8)
		(green b8)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?x) (or (not (green ?x)) (exists (?y) (and (maroon ?y) (on ?x ?y))))) (and (not (on b0 t0)) (not (on b0 b3)) (not (on b0 b4)) (not (on b0 b5)))))
)