(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b0)
		(clear b0)
		(on-table b1)
		(clear b1)
		(on-table b2)
		(clear b2)
		(on-table b3)
		(clear b3)
		(on-table b4)
		(clear b4)
		(on-table b6)
		(clear b6)
		(on-table b7)
		(clear b7)
		(clear b8)
		(in-tower t0)
		(on b9 t0)
		(in-tower b9)
		(on b5 b9)
		(in-tower b5)
		(on b8 b5)
		(in-tower b8)
		(red b0)
		(red b1)
		(blue b1)
		(red b3)
		(blue b3)
		(red b4)
		(red b5)
		(blue b6)
		(blue b8)
		(blue b9)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?y) (or (not (blue ?y)) (exists (?x) (and (red ?x) (on ?x ?y))))) (and (not (on b8 b9)) (not (on b7 b9)) (not (on b6 b9)) (not (on b7 b8)) (not (on b6 b8)) (not (on b4 b8)) (not (on b3 b8)) (not (on b2 b8)))))
)