(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(clear b2)
		(on-table b3)
		(clear b3)
		(on-table b4)
		(clear b4)
		(on-table b5)
		(clear b5)
		(on-table b6)
		(clear b6)
		(in-tower t0)
		(on b9 t0)
		(in-tower b9)
		(on b8 b9)
		(in-tower b8)
		(on b7 b8)
		(in-tower b7)
		(on b0 b7)
		(in-tower b0)
		(on b1 b0)
		(in-tower b1)
		(on b2 b1)
		(in-tower b2)
		(green b0)
		(blue b0)
		(green b1)
		(red b1)
		(blue b1)
		(green b2)
		(yellow b2)
		(blue b2)
		(green b3)
		(yellow b3)
		(blue b3)
		(blue b4)
		(green b5)
		(yellow b5)
		(green b6)
		(blue b6)
		(blue b7)
		(green b8)
		(red b8)
		(blue b8)
		(green b9)
		(blue b9)
		(blue b5)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?y) (or (not (yellow ?y)) (exists (?x) (and (green ?x) (on ?x ?y))))) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (and (not (on b6 b7)) (not (on b3 b2)) (not (on b5 b2)))))
)