(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b0)
		(clear b0)
		(clear b4)
		(on-table b5)
		(clear b5)
		(on-table b7)
		(clear b7)
		(on-table b8)
		(clear b8)
		(on-table b9)
		(clear b9)
		(in-tower t0)
		(on b1 t0)
		(in-tower b1)
		(on b6 b1)
		(in-tower b6)
		(on b2 b6)
		(in-tower b2)
		(on b3 b2)
		(in-tower b3)
		(on b4 b3)
		(in-tower b4)
		(red b0)
		(blue b1)
		(blue b4)
		(red b6)
		(red b7)
		(blue b0)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?y) (or (not (blue ?y)) (exists (?x) (and (red ?x) (on ?x ?y))))) (and (not (on b0 b1)) (not (on b0 b4)) (not (on b5 b4)) (not (on b8 b4)))))
)