(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b1)
		(clear b1)
		(on-table b2)
		(clear b2)
		(on-table b3)
		(clear b3)
		(on-table b4)
		(clear b4)
		(clear b5)
		(on-table b6)
		(clear b6)
		(on-table b9)
		(clear b9)
		(in-tower t0)
		(on b0 t0)
		(in-tower b0)
		(on b7 b0)
		(in-tower b7)
		(on b8 b7)
		(in-tower b8)
		(on b5 b8)
		(in-tower b5)
		(blue b0)
		(red b2)
		(blue b2)
		(blue b4)
		(maroon b4)
		(blue b5)
		(blue b6)
		(green b6)
		(maroon b6)
		(blue b7)
		(green b9)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?x) (or (not (green ?x)) (exists (?y) (and (maroon ?y) (on ?x ?y))))) (and (not (on b2 b0)) (not (on b2 b7)) (not (on b2 b5)))))
)