(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b1)
		(clear b1)
		(on-table b2)
		(clear b2)
		(on-table b3)
		(clear b3)
		(on-table b4)
		(clear b4)
		(on-table b5)
		(clear b5)
		(on-table b6)
		(clear b6)
		(clear b7)
		(in-tower t0)
		(on b8 t0)
		(in-tower b8)
		(on b0 b8)
		(in-tower b0)
		(on b9 b0)
		(in-tower b9)
		(on b7 b9)
		(in-tower b7)
		(red b0)
		(blue b0)
		(blue b1)
		(blue b2)
		(red b3)
		(green b4)
		(red b5)
		(yellow b6)
		(blue b7)
		(blue b8)
		(green b9)
		(red b2)
		(red b9)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?y) (or (not (yellow ?y)) (exists (?x) (and (green ?x) (on ?x ?y))))) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?y) (or (not (blue ?y)) (exists (?x) (and (red ?x) (on ?x ?y))))) (and (not (on b5 b0)) (not (on b3 b0)) (not (on b6 b7)))))
)