(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(clear b0)
		(on-table b3)
		(clear b3)
		(on-table b4)
		(clear b4)
		(on-table b5)
		(clear b5)
		(on-table b6)
		(clear b6)
		(in-tower t0)
		(on b1 t0)
		(in-tower b1)
		(on b2 b1)
		(in-tower b2)
		(on b8 b2)
		(in-tower b8)
		(on b9 b8)
		(in-tower b9)
		(on b7 b9)
		(in-tower b7)
		(on b0 b7)
		(in-tower b0)
		(red b0)
		(green b4)
		(maroon b4)
		(blue b3)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?x) (or (not (green ?x)) (exists (?y) (and (maroon ?y) (on ?x ?y))))) (and (not (on b8 b1)) (not (on b0 b1)) (not (on b0 b8)) (not (on b6 b7)) (not (on b6 b0)))))
)