(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b4)
		(clear b4)
		(clear b8)
		(on-table b9)
		(clear b9)
		(in-tower t0)
		(on b1 t0)
		(in-tower b1)
		(on b3 b1)
		(in-tower b3)
		(on b0 b3)
		(in-tower b0)
		(on b5 b0)
		(in-tower b5)
		(on b6 b5)
		(in-tower b6)
		(on b7 b6)
		(in-tower b7)
		(on b2 b7)
		(in-tower b2)
		(on b8 b2)
		(in-tower b8)
		(red b4)
		(blue b4)
		(blue b8)
		(red b2)
		(maroon b0)
		(maroon b1)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (forall (?y) (or (not (blue ?y)) (exists (?x) (and (red ?x) (on ?x ?y))))) (forall (?x) (or (not (green ?x)) (exists (?y) (and (maroon ?y) (on ?x ?y))))) (not (on b9 b8))))
)