(define (problem block-problem)
	(:domain blocksworld)
	(:objects b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 t0)
	(:init 
		(arm-empty )
		(on-table b0)
		(clear b0)
		(clear b4)
		(on-table b6)
		(clear b6)
		(in-tower t0)
		(on b8 t0)
		(in-tower b8)
		(on b9 b8)
		(in-tower b9)
		(on b7 b9)
		(in-tower b7)
		(on b5 b7)
		(in-tower b5)
		(on b3 b5)
		(in-tower b3)
		(on b2 b3)
		(in-tower b2)
		(on b1 b2)
		(in-tower b1)
		(on b4 b1)
		(in-tower b4)
		(blue b0)
		(yellow b1)
		(green b3)
		(blue b3)
		(yellow b5)
		(green b6)
		(red b6)
		(yellow b7)
		(green b8)
		(blue b8)
		(green b9)
		(red b9)
		(yellow b2)
	)
	(:goal (and (forall (?x) (in-tower ?x)) (forall (?x) (or (not (green ?x)) (exists (?y) (and (yellow ?y) (on ?x ?y))))) (forall (?y) (or (not (yellow ?y)) (exists (?x) (and (green ?x) (on ?x ?y))))) (forall (?x) (or (not (red ?x)) (exists (?y) (and (blue ?y) (on ?x ?y))))) (and (not (on b9 t0)) (not (on b6 b7)) (not (on b6 b5)) (not (on b4 b5)) (not (on b6 b3)) (not (on b4 b3)) (not (on b6 b2)) (not (on b4 b2)) (not (on b6 b1)) (not (on b6 b4)))))
)